
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 21 22:05:58 CST 2017
//----------------------------------------------------

package mpascal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Comma = 39;
  public static final int Or = 11;
  public static final int Begin = 22;
  public static final int End = 23;
  public static final int Until = 29;
  public static final int Sum = 13;
  public static final int LPar = 43;
  public static final int Repeat = 28;
  public static final int If = 19;
  public static final int Id = 42;
  public static final int Of = 31;
  public static final int GreaterThan = 6;
  public static final int Equal = 4;
  public static final int Var = 32;
  public static final int Else = 21;
  public static final int Read = 3;
  public static final int Semicolon = 50;
  public static final int Times = 15;
  public static final int Then = 20;
  public static final int Assign = 41;
  public static final int Colon = 40;
  public static final int BooleanLit = 53;
  public static final int NotEqual = 5;
  public static final int While = 27;
  public static final int To = 25;
  public static final int LessEqualThan = 9;
  public static final int LBracket = 37;
  public static final int For = 24;
  public static final int EOF = 0;
  public static final int Function = 47;
  public static final int Not = 12;
  public static final int And = 10;
  public static final int error = 1;
  public static final int RPar = 44;
  public static final int GreaterEqualThan = 8;
  public static final int Integer = 35;
  public static final int Divided = 17;
  public static final int Char = 34;
  public static final int Div = 18;
  public static final int Do = 26;
  public static final int Dot = 49;
  public static final int LessThan = 7;
  public static final int String = 36;
  public static final int StringLit = 54;
  public static final int Mod = 16;
  public static final int CharLit = 52;
  public static final int Array = 30;
  public static final int Boolean = 33;
  public static final int Minus = 14;
  public static final int IntLit = 51;
  public static final int Write = 2;
  public static final int Program = 45;
  public static final int RBracket = 38;
  public static final int Procedure = 46;
  public static final int DotDot = 48;
}

